apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pod-security-admission.fullname" . }}-controller-manager
  labels:
  {{- include "pod-security-admission.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      control-plane: controller-manager