apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-security-admission.fullname" . }}-pod-security-admission-config
  labels:
  {{- include "pod-security-admission.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.podSecurityAdmissionConfig.configYaml | toYaml | indent
    1 }}