apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "pod-security-admission.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "pod-security-admission.labels" . | nindent 4 }}
spec:
  selfSigned: {}