apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "pod-security-admission.fullname" . }}-serving-cert
  labels:
  {{- include "pod-security-admission.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "pod-security-admission.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc
  - {{ include "pod-security-admission.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "pod-security-admission.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
