apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "pod-security-admission.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pod-security-admission.fullname" . }}-serving-cert
  labels:
  {{- include "pod-security-admission.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "pod-security-admission.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-baseline
  failurePolicy: Fail
  name: baseline.vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: NotIn
      values:
      - privileged
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - pods/ephemeralcontainers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "pod-security-admission.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-restricted
  failurePolicy: Fail
  name: restricted.vpod.kb.io
  namespaceSelector:
    matchExpressions:
    - key: pod-security.cybozu.com/policy
      operator: In
      values:
      - restricted
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - pods/ephemeralcontainers
  sideEffects: None