resources:
  - manager.yaml

images:
- name: pod-security-admission
  newTag: 0.2.0
  newName: quay.io/cybozu/pod-security-admission

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: manager-config
    files:
      - controller_manager_config.yaml
  - name: pod-security-admission-config
    files:
      - config.yaml
