name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33  # v3.1.1
      with:
        aqua_version: v2.44.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
