name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@v3.0.0 # v3.0.0
      with:
        aqua_version: v2.28.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
