name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@928a2ee4243a9ee8312d80dc8cbaca88fb602a91 # v2.2.0
      with:
        aqua_version: v2.17.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
