name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Small test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: ./.github/actions/aqua
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: make lint
      - run: make check-generate
      - run: make test
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - uses: ./.github/actions/aqua
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
        with:
          version: latest
          args: --snapshot --skip-publish --clean
