name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  go-version: 1.16
  cache-version: 2
jobs:
  test:
    name: Small test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Cache Tools
        id: cache-tools
        uses: actions/cache@v2
        with:
          path: |
            bin
          key: cache-${{ env.cache-version }}-go-${{ env.go-version }}-${{ hashFiles('Makefile') }}
      - run: make setup
        if: steps.cache-tools.outputs.cache-hit != 'true'
      - run: make lint
      - run: make test
  build-image:
    name: Build Container Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t quay.io/cybozu/pod-security-admission:latest .
