name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Small test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - run: make setup
      - run: make lint
      - run: make check-generate
      - run: make test
  build-image:
    name: Build Container Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t quay.io/cybozu/pod-security-admission:latest .
