name: Release
on:
  push:
    tags:
    - 'v*'
env:
  go-version: 1.18
  tag: ${GITHUB_REF#refs/tags/v}
  prerelease: ${{ contains(github.ref, '-') }}
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t quay.io/cybozu/pod-security-admission:latest .
      - name: Push docker image to Quay.io
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io
          echo "pushing image ..."
          docker tag quay.io/cybozu/pod-security-admission:latest quay.io/cybozu/pod-security-admission:${{ env.tag }}
          docker push quay.io/cybozu/pod-security-admission:${{ env.tag }}
          BRANCH=$(echo ${{ env.tag }} | cut -d "." -f 1-2)
          docker tag quay.io/cybozu/pod-security-admission:latest quay.io/cybozu/pod-security-admission:$BRANCH
          docker push quay.io/cybozu/pod-security-admission:$BRANCH
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-20.04
    container:
      image: quay.io/cybozu/golang:1.18-focal
    steps:
      - uses: actions/checkout@v3
      - run: make build/install.yaml
      - name: Create release
        run: |
          if ${{ env.prerelease }}; then
            PRERELEASE="-prerelease"
          fi
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u cybozu-go -r pod-security-admission -n v${{ env.tag }} ${PRERELEASE} -b "See [CHANGELOG.md](./CHANGELOG.md) for details." v${{ env.tag }} ./build/
