name: Renovate
on:
  schedule:
    - cron: '0 0 * * 2'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@2a87d1192eaa0cac92b6566233afedf68fd3472a # renovate v38.1.8
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
